### ISSUE TITLE
Keep logic away from templates

### ISSUE THREAD

**Issue by barretodavid** [rangle/angular-training-examples#11]
In the code example for the section `4.1-what-if` we have this code example:

``` js
@Component({
  selector: 'app-root',
  template: `<input
    type="button"
    value="{{ label }}"
    (click)="onClick()">
    <span *ngIf="label !='show'">{{ someString }}</span>`,
  styles: [``]
})
export class AppComponent {
  label = 'show';
  someString = 'What if you could conditionally show components?';
  onClick() {
      if (this.label === 'show') {
        this.label = 'hide';
      } else {
        this.label = 'show';
      }
  };
}
```

In my opinion is not a good practice to have logic in the template like `*ngIf="label !='show'"`, instead we should rely on boolean instances like `*ngIf="isVisible"` and delegate the logic to the class. Again, I can submit a PR if you agree.

**Comment by xorgy** [comment]
It seems like it obscures the meaning and introduces more code. I understand the desire to separate concerns, but I don't think it helps in this case. There are cases where the logic is more than a simple expression; I would support using a method in those cases.

In addition, you then need to think of a method name for `isVisible`, introducing more work and giving people the opportunity to accidentally mislead the next person who comes along by naming it incorrectly. 

I am, however, resistant to putting _mutating_ logic in the template. For example: I wouldn't toggle the show state in the `(click)` expression.

**Comment by xorgy** [comment]
The example is a bit contrived, though. I would instead do something like:

``` TypeScript
@Component({
  selector: 'app-root',
  template: `<button (click)="toggleShow()">{{ show? 'hide': 'show' }}</button>
    <template [ngIf]="show">{{ someString }}</template>`,
})
export class AppComponent {
  show = true;
  someString = 'What if you could conditionally show components?';
  toggleShow() {
    this.show = !this.show;
  };
}
```

**Comment by barretodavid** [comment]
That is better but I think I wouldn't talk about the special `<template>` tag just yet to not confuse people.

``` js
@Component({
  selector: 'app-root',
  template: `
    <button (click)="toggleShow()">{{ show? 'hide': 'show' }}</button>
    <span *ngIf="show">{{ someString }}</span>`,
})
export class AppComponent {
  show = true;
  someString = 'What if you could conditionally show components?';
  toggleShow() {
    this.show = !this.show;
  };
}
```

**Comment by xorgy** [comment]
You would definitely have a better idea of that. :- )

**Comment by bennett000** [comment]
- Template tags should definitely come later.  
- The logic was in the `*ngIf` to illustrate the flexibility of the templating system.  Although that is technically bad practice so let's go with the boolean solution.
